version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: demy-qdrant
    restart: unless-stopped
    ports:
      - "127.0.0.1:6333:6333"  # REST API (localhost only)
      - "127.0.0.1:6334:6334"  # gRPC (localhost only)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - traefik
      - demy_internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qdrant_storage:
    driver: local

networks:
  traefik:
    external: true
  demy_internal:
    driver: bridge
